spring:
  application:
    name: AI-Service

  mongodb:
    host: localhost
    port: 27017
    database: airecommendationfitness

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id:  activity-process-group
      key-Deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-Deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.use.type.headers: false
        spring.json.valus.default.type:
        spring.json.truested.packages: "*"

  jackson:
    default-property-inclusion: non_null

    deserialization:
      fail-on-unknown-properties: false

app:
  kafka:
    topic:
      name: activity-fitness

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/

server:
  port: 8083

